### ISSUE TITLE
feature: set controls on/off and zoom in config

### ISSUE THREAD

**Issue by Sp4M** [vicmora/MMM-GoogleMapsTraffic#1]
Hi, it will be very usefull for smart mirrors application to give the possibility to hide UI controls (zoom and street view buttons)

this can be done by setting `disableDefaultUI: true` with "zoom" and "center" options.

What about adding a boolean disableDefaultUI to the config.js ?
By the way, we can also imagine to add a zoom parameter to the config.

It will end up with something like that:
```
config: 
            {
                key: 'YOUR_KEY',
                lat: 37.8262306,
                lng: -122.2920096,
                height: '300px',
                width: '300px',
                zoom: 10,
                disableDefaultUI: true
            }
```

**Comment by Sp4M** [comment]
I created a pull request for that

**Comment by quedayone** [comment]
I would like this as well.

**Comment by LexJackson** [comment]
Sp4M I just wanted to thank you for adding the pull request.. Would love to have this committed.. if the vicmora doesn't commit do we fork?

**Comment by LexJackson** [comment]
...nevermind :-) I figured it out.. Just a little green to git is all. Thanks for you hard work!

**Comment by vicmora** [comment]
added, sorry for the delayQ
