### ISSUE TITLE
Error in config file

### ISSUE THREAD

**Issue by athanast6** [vicmora/MMM-GoogleMapsTraffic#17]
Hello,
First off, let me say I have no idea what I'm doing.
I copy and pasted the config example from the readme file into my config.js. However, I get an error saying there is a problem with my config.js file. I have also created a Google Maps Javascript API key with restrictions to maps.google.com. I made sure to include this in config.js.
I am not sure what I have done wrong, maybe it is something to do with my API Key? Thanks for the help

**Comment by Stephan3555** [comment]
Stumbled over this as well.
The problem is that there is a syntax error in the config example:

There is no comma after the "width: '300px'"
