### ISSUE TITLE
Adjust position of module?

### ISSUE THREAD

**Issue by hockenator** [vicmora/MMM-GoogleMapsTraffic#3]
Hello, 
currently the modul is placed at the left side. 
Is there a possibility to place the module in the center of the screen or anywhere else?
Regards, Christoph

**Comment by screechyboy79** [comment]
Hi,

I achieved this by adding position: "top_center" after module: "MMM-GoogleMapsTraffic"

Thanks

Steve

**Comment by darkogor** [comment]
position: 'bottom_right',

**Comment by vicmora** [comment]
take a look here, pretty helpful
https://forum.magicmirror.builders/topic/286/regions
